### ISSUE TITLE
pip install on Windows: including path issue in examples

### ISSUE THREAD

**Issue by shengshuyang** [andre-martins/AD3#12]
I had some problems installing ad3 using `pip install`, and solved it by downloading the trunk, go to each of the headers under the folder `/example/` and change the `#include` statements. 

For example, in `\examples\dense\FactorBinaryTreeCounts.h` I replaced 

`#include "ad3/GenericFactor.h"` 

with

`#include "../../ad3/GenericFactor.h"`

My workaround is basically hard coding relative paths... Could this be solved with a more elegant way such as updating the makefile?

**Comment by amueller** [comment]
the pip install version is pretty old, and it might be fixed in master.
By trunk, do you mean the master in this repo?

**Comment by shengshuyang** [comment]
Yes I meant the master branch.

**Comment by shengshuyang** [comment]
Confirmed that the issue has been fixed. Closing issue.
