### ISSUE TITLE
need mote than 3 values to unpack

### ISSUE THREAD

**Issue by SebastienTs** [andre-martins/AD3#14]
Got this crash when executing one of PyStruct webpage [examples](http://pystruct.github.io/auto_examples/plot_exact_learning.html#sphx-glr-auto-examples-plot-exact-learning-py). The error comes from an AD3 internal function:

E:\Anaconda2\lib\site-packages\ad3\simple_inference.pyc in general_graph(unaries, edges, edge_weights, verbose, n_iterations, eta, exact)
     76     if exact:
     77         value, marginals, edge_marginals, solver_status =\
---> 78             factor_graph.solve_exact_map_ad3()

I installed Pystruct on latest Anaconda 2 32-bit (Python 2.7) under Windows 7 x64 with the following lines (VC for Python 2.7 was installed first):

> pip install https://github.com/andre-martins/AD3/archive/master.zip
> pip install pystruct
> conda install -c https://conda.anaconda.org/omnia cvxopt

Best,
Sébastien

**Comment by vene** [comment]
Hi Sebastien,

There used to be a difference between the API of AD3 from this repo and the one from the pystruct fork, the former did not return the `solver_status` from the `solve_exact` function.

This is no longer the case, this official repo as of version 2.1 is fully compatible with pystruct, while exposing more functionality in the wrapper.

Sorry for the late response! I believe this is fixed now, but feel free to reopen and let me know if not.
